CREATE DATABASE library_db;
USE library_db;

CREATE TABLE BOOK (
    bookId INT AUTO_INCREMENT PRIMARY KEY,
    bookName VARCHAR(200) NOT NULL,
    quantity INT CHECK (quantity >= 0),
    price DECIMAL(10,2) DEFAULT 5000
);

ALTER TABLE BOOK
ADD deadline DATE;

CREATE TABLE BORROW_BOOKS (
    borrowId INT AUTO_INCREMENT PRIMARY KEY,
    bookId INT,
    borrowDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bookId) REFERENCES BOOK(bookId)
);
